name: educatly
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  another_flushbar: ^1.12.30
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  easy_image_viewer: ^1.5.1
  chat_bubbles: ^1.6.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
